version: '3.8'

services:
  app:
    build: .
    image: flight-tracking:latest
    container_name: flight_tracker_instance
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app